services:
  app:
    build:
      context: .
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
    ports:
      - ${ASPNETCORE_HTTP_PORTS:-3000}:3000
